import type { InstructorExperience } from "@/lib/instructor/redesign-data";

/**
 * Synthetic, non-customer data for authenticated UI screenshots.
 *
 * The fixture is only rendered by the visual-fixture route, whose layout
 * returns a 404 unless VISUAL_FIXTURES_ENABLED=true.
 */
export const instructorVisualFixture: InstructorExperience = {
  profile: {
    name: "Sanne de Vries",
    role: "Instructeur",
    status: "Beschikbaar",
    tenantName: "Rijschool Horizon",
    email: "sanne@example.test",
    phone: "+31 6 12345678",
    ris20Qualified: true,
  },
  stats: [
    {
      label: "Lessen vandaag",
      value: "6",
      hint: "5 bevestigd",
      tone: "blue",
    },
    {
      label: "Proeflessen",
      value: "1",
      hint: "om 13:15",
      tone: "purple",
    },
    {
      label: "Examens",
      value: "1",
      hint: "morgen 09:30",
      tone: "rose",
    },
    {
      label: "Open taken",
      value: "3",
      hint: "1 met prioriteit",
      tone: "green",
    },
  ],
  appointments: [
    {
      id: "appointment-1",
      type: "lesson",
      title: "Rijles - bijzondere verrichtingen",
      studentName: "Noah Jansen",
      startsAt: "08:30",
      endsAt: "10:00",
      duration: "90 min",
      location: "Stationsplein 12, Utrecht",
      vehicle: "Volkswagen Golf - K-123-NX",
      status: "confirmed",
      href: "/instructeur/lessen/appointment-1",
    },
    {
      id: "appointment-2",
      type: "lesson",
      title: "Rijles - snelweg",
      studentName: "Mila Bakker",
      startsAt: "10:15",
      endsAt: "11:45",
      duration: "90 min",
      location: "Kanaalweg 44, Utrecht",
      vehicle: "Volkswagen Golf - K-123-NX",
      status: "confirmed",
      href: "/instructeur/lessen/appointment-2",
    },
    {
      id: "appointment-3",
      type: "trial",
      title: "Proefles",
      studentName: "Yara Visser",
      startsAt: "13:15",
      endsAt: "14:15",
      duration: "60 min",
      location: "NXTDRIVE leslocatie",
      vehicle: "Volkswagen Golf - K-123-NX",
      status: "planned",
      href: "/instructeur/lessen/appointment-3",
    },
    {
      id: "appointment-4",
      type: "admin",
      title: "Administratie",
      startsAt: "14:30",
      endsAt: "15:00",
      duration: "30 min",
      location: "Rijschoolkantoor",
      status: "planned",
      href: "/instructeur/agenda",
    },
    {
      id: "appointment-5",
      type: "lesson",
      title: "Rijles - examenroute",
      studentName: "Finn Smit",
      startsAt: "15:15",
      endsAt: "16:45",
      duration: "90 min",
      location: "CBR Utrecht",
      vehicle: "Volkswagen Golf - K-123-NX",
      status: "confirmed",
      href: "/instructeur/lessen/appointment-5",
    },
  ],
  students: [
    {
      id: "student-1",
      name: "Noah Jansen",
      license: "Rijbewijs B",
      progress: 68,
      status: "attention",
      nextLesson: "Vandaag, 08:30",
      latestLesson: "27 juli 2026",
      phone: "+31 6 11111111",
      email: "noah@example.test",
      attention: "Extra aandacht voor kijktechniek bij kruispunten.",
      readiness: "6 tot 8 lessen",
    },
    {
      id: "student-2",
      name: "Mila Bakker",
      license: "Rijbewijs B",
      progress: 82,
      status: "exam",
      nextLesson: "Vandaag, 10:15",
      latestLesson: "25 juli 2026",
      phone: "+31 6 22222222",
      email: "mila@example.test",
      attention: "Proefexamen voorbereiden en zelfstandige route oefenen.",
      readiness: "Examenklaar",
    },
    {
      id: "student-3",
      name: "Finn Smit",
      license: "Rijbewijs B",
      progress: 54,
      status: "active",
      nextLesson: "Vandaag, 15:15",
      latestLesson: "24 juli 2026",
      phone: "+31 6 33333333",
      email: null,
      attention: "Doseren en afstand houden op hogere snelheid.",
      readiness: "10 tot 12 lessen",
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Leskaart afronden",
      subject: "Noah Jansen",
      due: "Voor 10:15",
      priority: "high",
      status: "today",
    },
    {
      id: "task-2",
      title: "Proefexamen plannen",
      subject: "Mila Bakker",
      due: "Vandaag",
      priority: "medium",
      status: "open",
    },
    {
      id: "task-3",
      title: "Beschikbaarheid augustus",
      subject: "Persoonlijke planning",
      due: "Deze week",
      priority: "low",
      status: "open",
    },
  ],
  messages: [
    {
      id: "thread-1",
      name: "Mila Bakker",
      role: "Leerling",
      preview: "Kunnen we de ophaallocatie aanpassen?",
      time: "08:04",
      unread: 1,
      messages: [
        {
          id: "message-1",
          sender: "student",
          body: "Kunnen we de ophaallocatie aanpassen?",
          time: "08:04",
        },
      ],
    },
    {
      id: "thread-2",
      name: "Noah Jansen",
      role: "Leerling",
      preview: "Dankjewel, tot straks!",
      time: "gisteren",
      unread: 0,
      messages: [
        {
          id: "message-2",
          sender: "student",
          body: "Dankjewel, tot straks!",
          time: "gisteren",
        },
      ],
    },
  ],
  vehicles: [
    {
      id: "vehicle-1",
      name: "Volkswagen Golf",
      plate: "K-123-NX",
      transmission: "Handgeschakeld",
      status: "active",
      apk: "12 maart 2027",
      mileage: "48.320 km",
      maintenance: "Over 4.800 km",
    },
  ],
  evaluations: [
    {
      id: "evaluation-1",
      studentId: "student-1",
      studentName: "Noah Jansen",
      lessonLabel: "Les 18",
      lessonDate: "29 juli 2026",
      status: "todo",
      mode: "ris",
      modules: [
        {
          id: "module-1",
          name: "Module 2 - Voertuigbediening",
          completed: 3,
          total: 4,
          scripts: [
            {
              id: "script-1",
              index: 1,
              name: "Wegrijden en stoppen",
              score: "8",
              status: "ready",
            },
            {
              id: "script-2",
              index: 2,
              name: "Schakelen en snelheid",
              score: "7",
              status: "ready",
            },
            {
              id: "script-3",
              index: 3,
              name: "Bijzondere verrichtingen",
              score: "6",
              status: "attention",
            },
            {
              id: "script-4",
              index: 4,
              name: "Zelfstandig rijden",
              score: null,
              status: "open",
            },
          ],
        },
      ],
    },
  ],
  availability: [
    {
      day: "Maandag",
      active: true,
      start: "08:00",
      end: "17:30",
      breakLabel: "12:00 - 12:30",
    },
    {
      day: "Dinsdag",
      active: true,
      start: "08:00",
      end: "17:30",
      breakLabel: "12:00 - 12:30",
    },
    {
      day: "Woensdag",
      active: true,
      start: "09:00",
      end: "18:00",
      breakLabel: "12:30 - 13:00",
    },
    {
      day: "Donderdag",
      active: true,
      start: "08:00",
      end: "17:30",
      breakLabel: "12:00 - 12:30",
    },
    {
      day: "Vrijdag",
      active: true,
      start: "08:00",
      end: "16:00",
      breakLabel: "12:00 - 12:30",
    },
    {
      day: "Zaterdag",
      active: false,
      start: "",
      end: "",
      breakLabel: "Niet beschikbaar",
    },
    {
      day: "Zondag",
      active: false,
      start: "",
      end: "",
      breakLabel: "Niet beschikbaar",
    },
  ],
  availabilityToday: {
    availableMinutes: 540,
    bookedMinutes: 420,
    utilizationPct: 78,
    intervalLabel: "08:00 - 17:30",
    sourceLabel: "Weekschema",
  },
  radar: [
    {
      id: "radar-1",
      student: "Noah Jansen",
      reason: "Kijktechniek opnieuw beoordelen",
      priority: "high",
    },
    {
      id: "radar-2",
      student: "Mila Bakker",
      reason: "Proefexamen inplannen",
      priority: "medium",
    },
    {
      id: "radar-3",
      student: "Finn Smit",
      reason: "Lesdoel snelweg bevestigen",
      priority: "low",
    },
  ],
  nextAction: {
    reasonCode: "NEXT_LESSON",
    title: "Les van Noah voorbereiden",
    reason: "Dit is je eerstvolgende geplande afspraak.",
    urgency: "Over 20 min",
    subject: "Noah Jansen",
    time: "08:30 - 10:00",
    href: "/instructeur/lessen/appointment-1",
  },
};
